### ISSUE TITLE
Example of tooltip in documentation doesn’t work

### ISSUE THREAD

**Issue by leafac** [racket/drracket#113]
[This section](https://docs.racket-lang.org/tools/Check_Syntax.html?q=check%20syntax#%28part._.Syntax_.Properties_that_.Check_.Syntax_.Looks_.For%29) of the documentation includes the following example:

```racket
#lang racket
(define-syntax (char-span stx)
  (syntax-case stx ()
    [(_ a)
     (syntax-property
      #'a
      'mouse-over-tooltips
      (vector
       stx
       (syntax-position stx)
       (+ (syntax-position stx)
          (syntax-span stx))
       (format "this expression\nspans ~a chars"
               (syntax-span stx))))]))
 
(char-span (+ 1 2))
```

Supposedly, DrRacket should add a tooltip, but it doesn’t:

![bug-report](https://cloud.githubusercontent.com/assets/586813/26004176/effc17f2-3702-11e7-82dd-2973dac378b9.gif)

**Comment by dfeltey** [comment]
It's not immediately obvious to me why the original program isn't getting the tooltip, but this version of the macro seems to work:

```
(define-syntax (char-span stx)
  (syntax-case stx ()
    [(_ a)
     (syntax-property
      #'a
      'mouse-over-tooltips
      (vector
       stx
       (sub1 (syntax-position stx))
       (sub1 (+ (syntax-position stx)
                (syntax-span stx)))
       (format "this expression\nspans ~a chars"
               (syntax-span stx))))]))
```

**Comment by dfeltey** [comment]
It also seems that if you add a space or a newline following the `(char-span (+ 1 2))` expression then the tooltips do show up as well.

**Comment by leafac** [comment]
I can confirm that both your observations are correct: either the modified version or adding a new line fix the issue. It seems more of a corner case that I initially thought—do you think it’s a bug?

**Comment by dfeltey** [comment]
It does seem like a bug that probably has to do with the fact that syntax-positions start at 1 whereas editor positions start at 0, @rfindler any thoughts? I can try to look more into it this weekend since I've been looking at the check-syntax tooltip code recently.

**Comment by rfindler** [comment]
I haven't had time to have a look yet. But I do think that the original code should probably work (and I guess it did at one point). Having to put the `sub1`s in there seems bad.

**Comment by david-christiansen** [comment]
Adding an additional space to the end of the file does make the example code show the tooltip. However, the tooltip starts one character into the region that should be highlighted and persists one character past it (the space has the tooltip, but the opening paren does not).

Current DrRacket tooltip producers, including some that I've written, do include the `sub1` in practice so that the tooltips show up where they should. So it would not be backwards-compatible to add the `sub1` to https://github.com/racket/drracket/blob/56d6a1b3d822155dc33c495bf746c101bc352661/drracket-tool-lib/drracket/private/syncheck/traversals.rkt#L600-L603 .

It would, so far as I can tell, not break any existing tools to loosen up on the check here: https://github.com/racket/drracket/blob/f7d43855cf20c797925f73699b38540d3c6286e3/drracket/drracket/private/syncheck/gui.rkt#L1056
This conditional tests that the tooltip is within the editor's positions, rejecting them if not. Tooltips whose positions are out of the editor's range of positions could be truncated to display only in the valid positions, instead of being discarded. I think that this, together with `sub1` on the docs' code, would be a fix that doesn't break existing code.

Would you be interested in a patch to this effect?

**Comment by rfindler** [comment]
Good points about backwards compatibility. And yes, a patch would be welcome. Thank you.

**Comment by david-christiansen** [comment]
OK, I think that #144 takes care of this. Thanks!

**Comment by leafac** [comment]
Thank you, I learned from reading your conversation and pull request 😀
