### ISSUE TITLE
Stepper should maintain focus on most recent step

### ISSUE THREAD

**Issue by pnijjar** [racket/drracket#162]
This is an old version (6.7 on Linux) but I have observed this behaviour in 6.10 on Mac as well.

When I am in a teaching language (Beginner student through Intermediate Student with Lambda) and use the stepper for any nontrivial program, I get frustrated. The stepper is smart enough to show the changed values in purple and green, but it refreshes the UI and resets the focus to the top of the window. This means I have to scroll down for every single step. This makes the stepper nearly unusable for actually debugging code (as opposed to playing with short toy examples).

The stepper should either remember how much we have scrolled down on the last step and reset the scrollbar to that, figure out how much scrolling is necessary to put the purple/green highlighting at the top of the screen, or just retain the previous scrolling somehow.

**Comment by jbclements** [comment]
mea maxima culpa. I should fix this. I *should* have fixed this years ago. Maybe I'll do it tomorrow.

**Comment by pnijjar** [comment]
At  the risk of being a jerk: What is the probability of this getting fixed (and released) by mid-August or so? If the probability is good then I can request that the IT staff refresh Dr Racket on lab computers after the release. If this is not likely to be fixed by then I won't request anything from IT. 

This is not to pressure you into dropping everything and fixing the bug -- after all, I am not offering a pull request myself. But getting the fix for the upcoming fall term would be nice if it is feasible.

**Comment by rfindler** [comment]
If I have the release timeline straight, then the fix would have to come in today, I believe. (Is that right @stamourv ?)

**Comment by jbclements** [comment]
Sigh. Not going to happen today. @pnijjar : you are 100% not being a jerk. The only way this is going to get done is if you keep reminding me. Sigh again. I estimate that this would be a day or two of work. Let me just think out loud about the steps required.

* the code for highlighting is a bit nairy because of the back-and-forth with the pretty-printer, but I don't think that this change would require any additional complexity. There's definitely a call to the UI that says "turn this part purple", and at that point you know the buffer offsets of the highlighted region.

* there could be more than one highlighted region, but the "just pick the first one" strategy would work 98% of the time.

* I'm sure I'll mess up somehow in locking & unlocking the editor... or maybe setting the view doesn't even require unlocking the editor. Hopefully there's a UI call that allows you to set the scroll position by e.g. putting a particular piece of the editor at the top of the view... not sure.

Yeah actually it might be really easy. Maybe I'll get time today after sketching out a sigcse paper. 

do. not. hold. your. breath.

but keep reminding me!

**Comment by rfindler** [comment]
You could probably do a first cut that looked at the view size and position via the editor's admin, saving it before updating the buffer and then restoring it afterwards. (You could save the center point of the old view as a percentage distance from the top-left and then restore it that way.)

This wouldn't make things relative to the purple & green, but it might be what people would expect, anyway. It shouldn't be hard once you find the right calls (sigh, GUI programming.)

**Comment by stamourv** [comment]
@rfindler: You have the timeline correct. The post-beta testing period should start as soon as the merge-related discussions are concluded (and I return from my travel). So probably tomorrow.

**Comment by jbclements** [comment]
I'm closing this. It's not really "fixed" in the sense that it still doesn't ensure that the next step is in the window, but it does now scroll to the bottom, which is a huge huge huge improvement. Let me know if you don't agree that this issue should be closed.
