### ISSUE TITLE
DrRacket creates a "Root" window that interferes with Mac OS features

### ISSUE THREAD

**Issue by pnwamk** [racket/drracket#202]
Racket v6.12
macOS High Sierra (10.13.3)

Steps to reproduce:

1. Open the Terminal app (i.e. so there is a terminal app icon in the Mac OS tray)

2. Open DrRacket 6.12 from the applications folder

3-1. Press ctrl+up (or swipe up with 3 fingers) and note that the Mac OS "Mission Control" feature works (i.e. open windows are layed out in a tiled fashion).

3-2. Undo the mission control view (i.e. either by swiping back down, pressing ctrl+down, etc)

4. Click the red circle in top left corner to close drracket.

5. Click on the Terminal app in the Mac OS tray (i.e. so it switches focus to the open terminal window)

6. Click on DrRacket icon in the tray.

7. Click File>New (to open a new DrRacket window)

8. Press Cmd+Tab until DrRacket is highlighted, don't let Cmd go!

9. While still holding Cmd from previous step, press down arrow.

10. Note that there is a "Root" window associated with DrRacket.

11. Note that pressing Ctrl+Up (or swiping up w/ 3 fingers) to open the Mac OS "Mission Control" layout (i.e. where all open, non-minimized windows are layed out in a tiled fashion) no longer works! (By "no longer works" I mean the windows all go through the shrink and tile animation, but then they just keep shrinking until they disappear entirely.)

12. Close DrRacket entirely (i.e. quit out of the application so it no longer appears in the Mac OS tray) and note that the "Mission Control" feature works again!

Perhaps this is actually a Mac OS bug? Or it should be filed under a different racket repository? Anyway I figured I'd post it here for starters.

Here's the "Root" window mentioned in step 10:
<img width="1220" alt="screen shot 2018-04-07 at 8 57 54 pm" src="https://user-images.githubusercontent.com/3662058/38461760-8f59ede0-3aa6-11e8-8c2d-45fa9cf3178c.png">

**Comment by pnwamk** [comment]
Thanks @jbclements! I've updated the steps in light of your comments.

**Comment by jamesbornholt** [comment]
I think I tracked down the cause of this problem -- the Racket GUI toolkit creates [a fake window called "Root"](https://github.com/racket/gui/blob/135e357/gui-lib/mred/private/mrtop.rkt#L350), and immediately [hides it](https://github.com/racket/gui/blob/fb03ade/gui-lib/mred/private/wx/cocoa/frame.rkt#L727). But step 6 in this bug causes that root window to become visible again (because DrRacket.app gets reactivated with no other windows available, and this root window is ["sticky"](https://github.com/racket/gui/blob/fb03ade/gui-lib/mred/private/wx/cocoa/frame.rkt#L727)).

With racket/gui#111 applied, this issue doesn't happen for me any more (I tested various permutations of the instructions and could no longer reproduce).
