### ISSUE TITLE
DrRacket should not change the default file extension for all files

### ISSUE THREAD

**Issue by florence** [racket/drracket#26]
When a new collection has a `module-suffixes` drracket changes the default file extension for all files to that new extension. We probably want something language specific here.

Reported at: https://github.com/florence/pop-pl/issues/5

**Comment by rfindler** [comment]
This appears to be an issue with `put-file` under windows. Run this program and then type a filename without an extension, and the result is "y.pop" but it should be "y.rkt", at least according to my read of the documentation.

```
#lang racket/gui
(put-file
 "" #f #f #f
 "rkt" '()
 '(("Racket Sources" "*.pop;*.rkt;*.scm;*.scrbl;*.ss;*.rktd;*.rktl")
   ("Any" "*.*")))
```

**Comment by mflatt** [comment]
@rfindler I think the docs are misleading, assuming that you're referring to `Finally, if extension is any string other than the empty string, extension is used as the default extension when the user’s filters choice has the pattern "*.*"`. That's what happens if you run the program above and select "Any" before typing a filename without an extension.

If the user's filter choice is not `*.*`, then the docs currently don't say what happens. The sentence about deriving an extension should be revised to apply when the given default extension is any string and the selected filter is not `*.*`. (The current constraint to `""` is misleading.)

Meanwhile, it appears that the Windows dialog consistently "derives" an extension by using the first extension in the filter. That's not actually specified in the Windows documentation for `OPENFILENAME`, but neither is much of what the `put-file` docs already say.

**Comment by mflatt** [comment]
I've finally updated the docs. I also changed `get-module-suffixes` to always put "rkt" first in its result list – which is not a solution to the problem, but it makes the problem a little less bad for now.

**Comment by rfindler** [comment]
I think that @mflatt's fix mentioned above was actually the only thing to fix. In particular, if you want a language-specific extension, there's already a mechanism for that, documented here:

http://docs.racket-lang.org/tools/adding-languages.html?q=(append%20extra-default-filters%20(finder%3Adefault-filters))#%28idx._%28gentag._15._%28lib._scribblings%2Ftools%2Ftools..scrbl%29%29%29
