### ISSUE TITLE
In BSL number->string produces improper fraction when should produce decimal

### ISSUE THREAD

**Issue by jamie255** [racket/drracket#339]
In DrRacket 7.5 in vanilla Beginning Student, the following gives a decimal answer:

(/ (round (* 10000 (/ 48 147))) 100))

But (number->string (/ (round (* 10000 (/ 48 147))) 100))) produces "653/20"

**Comment by jbclements** [comment]
I ... don't think that's a bug. the result of the numerical operation is an exact number, a fraction. It's displayed in the beginner language interactions window as a decimal, but if you try (/ 1 3) you'll see a bar over the three; I think you really wouldn't want a "number->string" that produced numbers with bars over them. 

Maybe I should say: what behavior would you expect to see, here?

**Comment by jbclements** [comment]
BTW, if this is the Jamie Raymond that used to have a desk next to mine at Northeastern... hi!

**Comment by jamie255** [comment]
Sure, I can see that it might not be a bug, but the behavior is unexpected.
I would expect the string to be the same as the displayed number. My
students would be certainly be confused by this.

**Comment by mfelleisen** [comment]
DrRacket has many display options for numbers. If you right click (for some value on right) on the number, you can change the rendering of a number in DrRacket. So what you see in the Interactions Window is _not_ _the_ rendering of a number. ~~ I think this is a good teaching moment. 

Remember that you can also use #i (inexact) and #e (exact) for numbers. At some point this was early in HtDP because computer numbers are _not_ mathematical numbers and as much as try to hide the issue in BSL, we can't complete hide it.

**Comment by jamie255** [comment]
Thanks Matthias. I understand the underlying issue, although I was hoping to avoid the 'representation of numbers' discussion this early in the semester. I'm going to close this issue.
