### ISSUE TITLE
Last line of a file is not saved

### ISSUE THREAD

**Issue by yugenekr** [racket/drracket#353]
Hello,  
I'm new to DrRacket, so might be just missing some configuration parameter. 

DrRacket always shows one line more in the end of files, which leads to a confusion (and potentially to *No newline at end of file*) when adding a file to git or viewing it in another editor. Is there a way to fix this behavior so that a number of shown empty lines in the bottom of a file would actually match what vim/git sees? 
I'm using DrRacket v7.6 on MacOS.

<img width="440" alt="01-no-new-line" src="https://user-images.githubusercontent.com/296460/76145661-2fb46800-6094-11ea-976d-5fe3f178df0f.png">

<img width="447" alt="01-one-line" src="https://user-images.githubusercontent.com/296460/76145664-3642df80-6094-11ea-9469-aef3f0a037b3.png">

<img width="458" alt="01-two-lines" src="https://user-images.githubusercontent.com/296460/76145666-3ba02a00-6094-11ea-8aa6-ea43a6b02c6e.png">

**Comment by rfindler** [comment]
DrRacket is showing the actual content of the file; I think the other editors are not (they automatically add a newline at the end if there isn't actually one there).

Perhaps DrRacket should change so that it doesn't allow you to save a file that does not have a terminating newline (by adding one automatically), tho.

**Comment by yugenekr** [comment]
Actually, it's the opposite. Sorry, I made screenshots with confusingly ordered editors. DrRacket file is saved first, then I open it in vim.

So, in words: vim / git are lacking a line DrRacket would show. If I save a .rkt file (in DrRacket) with one empty line in the end, then git would end up showing *No new line at end of file*.

I assume in Emacs I would use `(setq require-final-newline t)` setting.
May [this DrRacket config](https://docs.racket-lang.org/tools/drracket_language.html?q=drracket#%28def._%28%28lib._drracket%2Ftool-lib..rkt%29._drracket~3alanguage~3asimple-settings-insert-newlines%29%29) help me to fix this issue? That's the only possibly related eol thing I could find in the docs.

Thanks.

**Comment by rfindler** [comment]
When you save a file that has, say, four bytes in it represented by this string "abcd" then git/vim will say, roughly, "I don't like this file because it doesn't end with a newline". DrRacket will show one line in that case. If you save a file that has five bytes in it represented by this string "abcd\n" then git/vim will be happy with it and DrRacket will show two lines (one with "abcd" and one blank).

Other editors ensure that there is always a terminating newline in the file; DrRacket shows you exactly what is in the file, terminating newline or not. 

(I hope this is clearer than my previous message.)

**Comment by yugenekr** [comment]
Yes, thank you very much for this explanation, you pointed me in the right direction. Oddly, I wasn't  aware vim and some other editors insert a newline automatically on save, in case an author didn't do it.

**Comment by rfindler** [comment]
In all seriousness, it is possible that DrRacket should do the more sophisticated thing (behaving like these other editors).

**Comment by yugenekr** [comment]
From my point of view and use case, having things happening explicitly, without hidden 'magic' is a preferred way. For example, this particular issue shows that if a person experiences a 'magic' all the time, then such a person would think this is a 'normal' way.

Maybe there're other use cases, but I personally don't see 'auto-newline' to be a required/mandatory feature (or even desired) at this time.
