### ISSUE TITLE
Example of file which makes the user wait for syntax-coloring to finish

### ISSUE THREAD

**Issue by soegaard** [racket/drracket#56]
This file:    https://github.com/soegaard/remacs/blob/master/editor.rkt
takes a *very* long time to color. 

To reproduce:
   1. Open it. 
   2. Press cmd+down
   3. Wait till the entire file is colored.

Waiting for the syntax-coloring becomes a real problem when strings are inserted.

Example:

   1. Go to line 1973 and type (one character at a time)
         ["D-S-
      when the syntax-coloring kicks in you, you are forced to wait 
      until the coloring is done.

**Comment by rfindler** [comment]
I'm not seeing unexpectedly bad behavior. More precisely, I do see it takes a while to color, but I'm not seeing bad interactivity because of it. In general, it should be the case that the colorer blocks only long enough to color a single token, not all of them. Are you seeing otherwise?

This code shows that it takes a long time to color the window initially (2.5 seconds on my machine), but that editing (quick typing simulated by the `for` loop) is interactive, which matches what I see when I perform the suggested edits.

I'm not doubting that you're seeing bad interactivity, but I am not able to see what it is that is causing it to happen for you. One guess is that you have some different preferences set that might somehow be causing the code to take a different path that has bad performace somewhere. To that end, what output do you see when you run the code below (just via racket from the command-line, in the same directory where "editor.rkt" is)?

```
#lang racket/gui
(require framework)
(collect-garbage) (collect-garbage) (collect-garbage)

(define t (new racket:text%))

(time
 (send t load-file "editor.rkt")
 (send t freeze-colorer))

(send t thaw-colorer)
(define p (send t paragraph-start-position 1973))
(send t set-position p p)
(printf "time ~a\n" (current-process-milliseconds))
(for ([char (in-list (string->list "[\"D-S-"))])
  (queue-callback
   (λ ()
     (printf "time ~a, inserting ~a\n" (current-process-milliseconds) char)
     (send t insert char))
   #f))
```

**Comment by rfindler** [comment]
Another question: when you go to that point in the file and just hold down the " key, what do you see? What I see is that sometimes the blue/green switches completely and sometimes it goes only part way down the file. What that means to me is that the interactivity is doing something right, at least, because the buffer is only partly re-colored before it decides to handle the next keystroke.

**Comment by soegaard** [comment]
I can't seem to reproduce the original results. Neither on 6.5 nor on 6.4.
(I have upgraded DrRacket)

Note also that editor.rkt has changed in the mean time (I should have
linked a specific version), so I tried both on the old and the new version.

I ran the program in 6.5 and got these results:

Welcome to DrRacket, version 6.5.0.5--2016-05-31(-/f) [3m].
Language: racket/gui, with debugging; memory limit: 1024 MB.
cpu time: 2287 real time: 2374 gc time: 80
time 1058389
time 1058420, inserting [
time 1058429, inserting "
time 1058430, inserting D
time 1058431, inserting -
time 1058431, inserting S
time 1058432, inserting -

With regards to the "-test, I think I am seeing the same as you.

If I see the same problem again, I will make a video.

I wonder whether I had some custom indenting rules that could have affected the
behaviour. I might have add rules  ^define-.* and ^with-.*  but I can't see them now.

**Comment by rfindler** [comment]
It does seem possible that indenting rules could affect things, since the colorer does take them into account. But the way it does is to match a string that's already delimited as a keyword (so should be short?) via regexp matching (so should be fast?).

A video would be helpful, thanks!

I'll close this for now, but please re-open if you see the symptoms again.
