### ISSUE TITLE
[Question] On MacOS raco installs DrRacket in ~/Library  how do you install into /Applications when you have installed Racket from minium source ?  

### ISSUE THREAD

**Issue by andrewcrook** [racket/drracket#565]
Installing DrRacket via `raco` it places `DrRacket.app` in the folder `~/Library/Racket/8.5/ `

- I think raco should install this within  `/Applications`  and subfolder `/Applications/Racket ${version}/` as to also support multiple versions.
- Can this be added to the package installer for installing on Macs? 

**Note:** I am not sure if this matters but I install racket via `racket-minimal-8.5-src-builtpkgs.tgz` then install packages via raco as and when needed.

**Comment by andrewcrook** [comment]
@sorawee  Thanks for getting back to me 

> convention

But its not a convention to install a MacOS app into `~/Library` as you say it should be in `/Applications`

The precompiled version of racket the I have alway dragged the `Racket XXX` folder into `/Applications` and it worked.

When using `racket-minimal-8.5-src-builtpkgs.tgz` and then `raco`,  whether the   `~/Library/Racket/8.5/DrRacket.app` can be just moved into `/Applications` or whether it needs to be built differently I don't know.  I just know it is not in right location at the moment.

**Comment by mflatt** [comment]
To elaborate on what @sowaree says (because I was already typing it):

If you install packages with just `raco pkg` or with `raco pkg -u`, then applications will go to a user-specific dierctory,. Use `raco pkg -i` to install into the Racket installation (instead of a user specific place), and then applications will be part of that installation.

So, if your Rackt installation is in `/Applications`, then `raco pkg -i` will put things like `DrRacket.app` there. But if your installation is in something like `/usr/local/racket`, then `DrRacket.app` will go there, instead.

You can change where installation applications are written by modifying `racket/etc/config.rktd`. Specifically, set `gui-bin-dir` as described at https://docs.racket-lang.org/raco/config-file.html to control where an application like `DrRacket.app` will go.

**Comment by andrewcrook** [comment]
@sorawee and @mflatt  Thank you both for your help. 

In order to make it work  I had to define `gui-bin-dir` in `racket/etc/config.rktd` and use the` -i` argument with `raco`
