### ISSUE TITLE
Background expansion masks `.zo` version error

### ISSUE THREAD

**Issue by shhyou** [racket/drracket#630]
## Version

Racket v8.10.0.2

## Description

The `.zo` version mismatch error is hidden in background expansion. The end result is that check syntax does not add any entry to the context menu of the respective `require`.

## Steps to reproduce

1. Enable “populate "compiled" directories” in Language > Choose Language.
2. Create `usr.rkt` and `lib.rkt` such that `usr.rkt` imports `lib.rkt`:
    ```
    ;; lib.rkt
    (module lib racket/base (define lib-N 456) (provide lib-N))
    ;; usr.rkt
    (module usr racket/base (require "lib.rkt") lib-N)
    ```
3. Compile (`raco make`) `lib.rkt` using Racket v8.9.
4. Open `usr.rkt` in DrRacket v8.10.
5. Right click on `"lib.rkt"`

## Actual behavior

Background expansion succeeded, with binding arrows and documentation annotations. However, the “open lib.rkt” entry of `require` in step 5 is missing.

## Expected behavior

Either there should be a `.zo` version mismatch error from background expansion or the entry “open lib.rkt” should exist.

Furthermore, clicking the Check Syntax button restores the desired menu item.

**Comment by rfindler** [comment]
Thanks!

It looks like the problem is that `use-compiled-file-paths` is not set to the right value during the call to [`get-require-filename`](https://github.com/racket/drracket/blob/06a747632ef32d737127527e53030afa36f165f8/drracket-tool-text-lib/drracket/private/syncheck/traversals.rkt#L1325), so we end up in the exception handler (as you write) because we looked in `compiled/` instead of `compiled/drracket/errortrace` (assuming the default language settings overall).

The trouble is that it isn't clear how to communicate this value (or avoid the need to communicate it which seems like it would be better as we'd be able to avoid the calls that interact with the filesystem!).

**Comment by rfindler** [comment]
Oh! Looks like I've been here before and my solution was [this blob of code](https://github.com/racket/drracket/blob/master/drracket/drracket/private/syncheck/online-comp.rkt#L46-L50). I'll update it to also propagate `use-compiled-file-paths`.
