### ISSUE TITLE
text/font should be able to draw outlined (stroked) text

### ISSUE THREAD

**Issue by schanzer** [racket/drracket#7]
Proposal: text/font should support a 9th argument (boolean), that causes the text to be rendered as white with a colored stroke. I considered overloading the "style" argument, but that seems like an uglier kludge. This change has been implemented (unofficially) in WeScheme (demo at http://192.wescheme.appspot.com/openEditor?publicId=fzUP5QlHU0).

Purpose: obviously, the most important use-case is for kids to make meme images. The second most important one is for adults to do so.

**Comment by rfindler** [comment]
How about another function called "text/meme" that accepts one extra color
argument (to be used as the stroke color)?

And are you imagining this being implemented via turning the letters into a
path and drawing the path with a pen? Or by overlaying two slightly
different font sizes? If the latter maybe best to just leave it out of the
library or to show that technique only in an example in the docs?

And finally this is the wrong repo. The 2htdp/image library is in the htdp
repo.

Robby

**Comment by ntoronto** [comment]
Plot and Pict3D draw outlined text to ensure text overlays (tick labels, 
position readouts) are always legible. It would be nice to have direct 
support if it's possible.

Here's my experience with outlined text.

Drawing in a larger font or in bold first doesn't work because the 
spacing between letters scales with font size and weight. Drawing one 
letter at a time helps as long as the foreground letters can be centered 
well enough, but loses kerning.

Plot draws the outline first by drawing the text 8 times at different 
offsets in the outline color. I think it does so because I didn't think 
the path outlines were thick enough, or something.

Pict3D uses paths. Drawing text with paths requires four method calls, 
which makes them annoying to use. Aside from this, some internal length 
limitation on paths forces Pict3D to break up text into chunks separated 
by spaces. Fortunately, the text always has enough spaces, so it can't 
lose kerning. There are weird little outline-colored dots on the lower 
right of each font outline path.

Alpha compositing doesn't work properly using any of these techniques, 
unless it's done in a separate buffer and pasted in.

Neil ⊥

**Comment by rfindler** [comment]
No engagement from Emmanuel.
